import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
const $=id=>document.getElementById(id),view=$('view');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));view.appendChild(renderer.domElement);
renderer.setClearColor(0x14212b);const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,1000);camera.position.set(45,90,70);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,0,0);orbit.minDistance=35;orbit.maxDistance=180;
scene.add(new T.HemisphereLight(0xffffff,0x718493,3));const light=new T.DirectionalLight(0xffffff,3);light.position.set(20,90,50);scene.add(light);
const overlays=new T.Group();scene.add(overlays);const roots={};let phase='mission',active='Naive',focused=null,compareBefore=false;
function render(){renderer.render(scene,camera)}orbit.addEventListener('change',render);
new ResizeObserver(()=>{renderer.setSize(view.clientWidth,view.clientHeight);camera.aspect=view.clientWidth/view.clientHeight;camera.updateProjectionMatrix();render()}).observe(view);
const element=(tag,text,cls)=>{const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e};
function button(text,fn){const b=element('button',text);b.onclick=fn;return b}
try{
 const [data,models]=await Promise.all(['results.json','models.json'].map(async url=>{const r=await fetch(url);if(!r.ok)throw Error(url);return r.json()}));
 const loader=new GLTFLoader();
 for(const [key,file] of [['Naive','initial.glb'],['MissionPCB','improved.glb']]){const gltf=await loader.loadAsync(file);const g=gltf.scene;g.scale.setScalar(1000);g.position.set(-136,0,-119);g.visible=false;scene.add(g);roots[key]=g;}
 for(const model of models){$('models').append(element('li',model.reference+' · '+model.role+': '+model.limitation))}
 const initial=data.results.Naive,improved=data.results.MissionPCB;
 const failures=initial.checks.filter(c=>c.status==='FAIL');
 const names=Object.fromEntries(initial.component_positions.map(p=>[p.ref,p.part_name]));
 const events=[];
 function event(text){events.push(text);$('transcript').replaceChildren(...events.map(t=>element('li',t)))}
 function mark(subjects,color=0xff5050){for(const p of data.results[active].component_positions){if(!subjects.has(p.ref))continue;const ring=new T.Mesh(new T.RingGeometry(4,4.6,48),new T.MeshBasicMaterial({color,side:T.DoubleSide,transparent:true,opacity:.85,depthTest:false}));ring.rotation.x=-Math.PI/2;ring.position.set(p.board_xy_mm[0]-36,2.2,19-p.board_xy_mm[1]);ring.renderOrder=5;overlays.add(ring)}}
 function drawBoard(){for(const [k,g] of Object.entries(roots))g.visible=k===active&&!['mission','parts'].includes(phase);while(overlays.children.length){const c=overlays.children[0];overlays.remove(c);c.geometry.dispose();c.material.dispose()}
 if(['review','proposal','compare'].includes(phase)&&active==='Naive'){const check=failures.find(c=>c.id===focused);mark(new Set((check?[check]:failures).flatMap(c=>c.subjects||[])),check?0x65d7ef:0xff5050)}render()}
 function moveTable(){const table=document.createElement('table');const head=document.createElement('tr');for(const s of ['Component','Before XY','After XY'])head.append(element('th',s));table.append(head);for(const a of initial.component_positions){const b=improved.component_positions.find(p=>p.ref===a.ref);const tr=document.createElement('tr');for(const value of [a.part_name,a.board_xy_mm.join(', '),b.board_xy_mm.join(', ')])tr.append(element('td',value));table.append(tr)}return table}
 function checkList(){for(const check of failures){const a=element('article','',check.id===focused?'selected':'');a.tabIndex=0;a.setAttribute('role','button');a.setAttribute('aria-label','Explain: '+check.message);a.setAttribute('aria-pressed',String(check.id===focused));a.append(element('strong',check.message));a.append(element('p',check.rationale||''));const choose=()=>{focused=check.id;event('Selected issue: '+check.message);update()};a.onclick=choose;a.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose()}};$('checks').append(a)}}
 function go(next){phase=next;focused=null;compareBefore=false;active=next==='compare'?'MissionPCB':'Naive';update()}
 function update(){const wf=$('workflow');wf.replaceChildren();$('checks').replaceChildren();$('improved').disabled=false;const titles={mission:['01 / MISSION','Start with one ECG mission','This replay uses a fixed ECG example. It does not send a request to Astra.','Load cached parts'],parts:['02 / INPUTS','Review parts and constraints','Six core component roles. These are the placement-demo inputs, not a complete electrical BOM.','Inspect initial board'],review:['03 / ATTENTION','Explain the flagged layout','Select a flag to highlight its components and inspect the rule.','Review proposed moves'],proposal:['04 / PROPOSAL','Review the placement changes','The board stays at its initial placement until you apply this cached proposal.','Apply cached proposal'],compare:['05 / COMPARE','See what changed','Compare the same cached checks across the two placement snapshots.','Restart demo']};const t=titles[phase];$('step').textContent=t[0];$('heading').textContent=t[1];$('instruction').textContent=t[2];$('improved').textContent=t[3];
 if(phase==='mission'){wf.append(element('p','“Lay out a single-lead ECG chest patch with BLE connectivity. Keep the sensitive ECG front end away from noisy and heat-producing parts.”','stageNote'));wf.append(element('p','Demo scope: 72 × 38 mm board · six core parts · cached placement checks.'));$('summary').textContent='ECG chest patch · cached demo';}
 if(phase==='parts'){const ul=document.createElement('ul');for(const p of initial.component_positions)ul.append(element('li',p.part_name+' — '+p.ref));wf.append(ul);wf.append(element('h3','Placement policies'));const rules=document.createElement('ul');for(const s of ['ECG front end to MCU: at least 18 mm center spacing.','ECG front end to regulator: at least 20 mm center spacing.','Charger and regulator zones: authored heat-clearance proxies.','Enclosure access and under-board patient/battery coverage: incomplete.'])rules.append(element('li',s));wf.append(rules);wf.append(element('p','AFE and regulator packages are approximations. Open Package accuracy below for details.','stageNote'));$('summary').textContent='Cached inputs ready · no network required';}
 if(phase==='review'){checkList();if(focused){const c=failures.find(c=>c.id===focused);wf.append(element('p','Focused: '+c.subjects.map(r=>names[r]||r).join(' + '),'selection'));wf.append(element('p',c.suggestion||'Review the proposed separation changes.'));wf.append(element('p','Rule source: authored demo policy. Geometry measurement from the cached engine snapshot.'));wf.append(button('Show all flags',()=>{focused=null;update()}))}else{$('improved').disabled=true;wf.append(element('p','Choose one issue below to continue.','stageNote'))}}
 if(phase==='proposal'){wf.append(element('p','Proposed coordinates in board-local millimeters:'));wf.append(moveTable());wf.append(element('p','Expected cached result: 5 → 0 failed checks; 2 remain skipped.','metric'));wf.append(element('p','This proposal moves all six core parts. Apply changes the replay view; it does not write into KiCad.'));wf.append(button('Back to issues',()=>go('review')))}
 if(phase==='compare'){wf.append(element('p','5 → 0 flagged checks','metric'));wf.append(element('p','21 → 26 passed · 2 skipped in both snapshots'));wf.append(button(compareBefore?'Viewing before':'Show before',()=>{compareBefore=true;active='Naive';focused=null;update()}),button(!compareBefore?'Viewing after':'Show after',()=>{compareBefore=false;active='MissionPCB';focused=null;update()}));wf.append(moveTable());wf.append(element('h3','Still unresolved'));for(const c of improved.checks.filter(c=>c.status==='SKIP'))wf.append(element('p',c.message));wf.append(element('p','No complete-design pass: routing and medical/physical validation are outside this replay.','stageNote'))}
 if(['review','proposal','compare'].includes(phase)){const r=data.results[active];$('summary').textContent=`${active==='Naive'?'Initial':'Improved'} placement · ${r.summary.FAIL} flags · ${r.summary.SKIP} skipped`;}drawBoard();}
 function reset(){events.length=0;event('Cached replay started. Explanations below are scripted, not a live model transcript.');go('mission')}
 $('initial').onclick=reset;$('improved').onclick=()=>{if(phase==='mission'){event('ECG mission selected. Loaded six cached core parts and authored placement policies.');go('parts')}else if(phase==='parts'){event('Loaded initial KiCad geometry and cached result: five failed checks, two skipped.');go('review')}else if(phase==='review'){event('Prepared cached six-part placement proposal; initial board unchanged.');go('proposal')}else if(phase==='proposal'){event('Applied cached proposal to replay viewer. Result: zero failed checks, two skipped.');go('compare')}else reset()};$('initial').disabled=false;reset();
}catch(error){$('error').textContent='Could not load cached demo: '+error.message;$('summary').textContent='Load failed';}
