"""Render advisor output as Markdown."""

from __future__ import annotations

from .schema import AdvisorOutput, Consideration

_SEVERITY_ORDER = {"blocker": 0, "major": 1, "minor": 2, "info": 3}

_ACTION_LABEL = {
    "replace": "Replace",
    "add": "Add",
    "remove": "Remove",
    "change_operating_point": "Change operating point",
    "add_constraint": "Add constraint",
    "investigate": "Investigate",
}


def _consideration(c: Consideration, index: int) -> list[str]:
    lines = [
        f"### {index}. {c.title}",
        "",
        f"`{c.id}` — **{_ACTION_LABEL.get(c.action, c.action)}** · "
        f"{c.severity} · {c.confidence} confidence",
        "",
    ]
    if c.subject_part_ids:
        lines.append(f"**Concerns:** {', '.join(f'`{p}`' for p in c.subject_part_ids)}")
    if c.proposed_part_ids:
        lines.append(f"**Proposed:** {', '.join(f'`{p}`' for p in c.proposed_part_ids)}")
    if c.subject_part_ids or c.proposed_part_ids:
        lines.append("")

    lines += [f"**What changes.** {c.what_changes}", ""]
    lines += [f"**Why.** {c.why}", ""]
    lines += [f"**Tradeoff.** {c.tradeoff}", ""]

    if c.evidence:
        lines.append("**Evidence**")
        lines.append("")
        for e in c.evidence:
            lines.append(f"- `{e.part_id}` — {e.fact}  \n  <sub>{e.citation}</sub>")
        lines.append("")
    else:
        lines += [
            "**Evidence.** None from the catalog — this rests on general "
            "engineering knowledge (see *Why*).",
            "",
        ]

    if c.engine_encoding:
        lines += [
            "**Checkable by the engine as:**",
            "",
            f"```\n{c.engine_encoding}\n```",
            "",
        ]
    return lines


def render(out: AdvisorOutput, mission_label: str = "", usage: dict | None = None) -> str:
    lines = ["# Design Considerations"]
    if mission_label:
        lines.append(f"\nMission: {mission_label}")
    lines += ["", "## Mission as understood", "", out.mission_summary, ""]

    ordered = sorted(
        out.considerations,
        key=lambda c: (_SEVERITY_ORDER.get(c.severity, 9), c.id),
    )

    counts: dict[str, int] = {}
    for c in ordered:
        counts[c.severity] = counts.get(c.severity, 0) + 1
    summary = ", ".join(f"{n} {sev}" for sev, n in sorted(
        counts.items(), key=lambda kv: _SEVERITY_ORDER.get(kv[0], 9)
    ))
    lines += [f"## Considerations ({len(ordered)}: {summary})", ""]

    for i, c in enumerate(ordered, start=1):
        lines += _consideration(c, i)

    if out.open_questions:
        lines += ["## Open questions", "",
                  "Answers to these would change the recommendations above.", ""]
        lines += [f"- {q}" for q in out.open_questions]
        lines.append("")

    if out.unmodeled_risks:
        lines += ["## Not assessed by this pass", ""]
        lines += [f"- {r}" for r in out.unmodeled_risks]
        lines.append("")

    lines += [
        "---",
        "",
        "*Generated by the MissionPCB advisor. Every recommendation here is a "
        "judgment call, not a measurement — the deterministic engine computes "
        "distances and pass/fail separately. Considerations marked with an "
        "engine encoding can be handed to it directly.*",
    ]

    if usage:
        lines += [
            "",
            f"<sub>tokens: {usage.get('input_tokens', 0)} in, "
            f"{usage.get('output_tokens', 0)} out, "
            f"{usage.get('cache_read_input_tokens', 0)} cache read</sub>",
        ]

    return "\n".join(lines) + "\n"
